name: build and test

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [develop]

jobs:
    build_app:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.24

            - name: Test
              run: go test -v ./...
            - name: Build
              run: go build -v ./...
